ReverseProxy:
    Routes:
        weather-service:
            ClusterId: weather-service
            Match:
                Path: '/v1/weather/{**catch-all}'
            Transforms:
                - PathRemovePrefix: '/v1'
        geo-service:
            ClusterId: geo-service
            Match:
                Path: '/v1/geo/{**catch-all}'
            Transforms:
                - PathRemovePrefix: '/v1'

    Clusters:
        weather-service:
            Destinations:
                weather-service-1:
                    Address: http://localhost:5000
        geo-service:
            Destinations:
                geo-service-1:
                    Address: http://localhost:5001
