OpenWeatherAPIKey: 66dd82dc3ad4ce128bbadc979c261787
eureka:
  client:
    shouldRegisterWithEureka: true
    serviceUrl: http://localhost:8761/eureka/
  # instance:
  #   port: 5000
  #   ipAddress: localhost
  #   preferIpAddress: true